### PR TITLE
Fixed few typos in entity-list.ts

### PR DESCRIPTION
**Pull request by asty8926**
I loved your portfolio and noticed on the very first dialog the word "intereact". At first I lowkey wondered if it was a play on words because you use Svelte (=/= React), but then I decided to edit the 2 mistakes I saw and help you in your project.

Congratulations for your portfolio and for creating Skeleton UI as well! :)

### CODE REVIEW

**Comment by endigo9740** [comment]
Thanks for the PR @asty8926 but we never allow PRs targeting the master branch. Under normal circumstance we would target `dev` branch instead. But while we're in the midst of prepping for v2, we're asking folks to please target the `v2` branch please. I won't be able to retarget this for you give you've likely based your change on the `master` branch. If you could please resubmit!

And thank you for the kind words!

**Comment by asty8926** [comment]
Alright, my apologies! I will remake the PR and target the `v2` branch then :)

**Comment by asty8926** [comment]
Hmm, I only see a `master` and a `staging` branch, but no `v2` or even `dev` branch in your `endigo-design` repository.
Am I missing something @endigo9740?

**Comment by endigo9740** [comment]
@asty8926 I'm so sorry. I manage an open source project called Skeleton and 99% of notifications I get are for PRs trying to merge into that. I thought the comment about my portfolio was a bit out of pocket! You actually had this right before. I'll reopen and review. Sorry for the confusion!

**Comment by endigo9740** [comment]
I've merged this now. Thanks again.

**Pull request merged**
